/*
 * Copyright (C) 2018 BlueKitchen GmbH
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holders nor the names of
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 * 4. Any redistribution, use, or modification is done solely for
 *    personal benefit and not for any commercial purpose or for
 *    monetary gain.
 *
 * THIS SOFTWARE IS PROVIDED BY BLUEKITCHEN GMBH AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL MATTHIAS
 * RINGWALD OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
 * THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * Please inquire about commercial licensing options at 
 * contact@bluekitchen-gmbh.com
 *
 */
#ifndef __CYCLING_POWER_SERVICE_SERVER_H
#define __CYCLING_POWER_SERVICE_SERVER_H

#include <stdint.h>

#if defined __cplusplus
extern "C" {
#endif

/**
 * Implementation of the GATT Cycling Power Service Server 
 */

// *****************************************************************************
/* GATT_SERVICE_SERVER_START(cycling_power_service_server){Cycling PowerService} 
 *
 */
// *****************************************************************************
/* GATT_SERVICE_SERVER_END */

/* API_START */

typedef enum {
	CP_MEASUREMENT_FLAG_PEDAL_POWER_BALANCE_PRESENT = 0,
	CP_MEASUREMENT_FLAG_PEDAL_POWER_BALANCE_REFERENCE, // 0 - unknown, 1 - left
	CP_MEASUREMENT_FLAG_ACCUMULATED_TORQUE_PRESENT,
	CP_MEASUREMENT_FLAG_ACCUMULATED_TORQUE_SOURCE, // 0 - wheel based, 1 - crank based
	CP_MEASUREMENT_FLAG_WHEEL_REVOLUTION_DATA_PRESENT,
	CP_MEASUREMENT_FLAG_CRANK_REVOLUTION_DATA_PRESENT,
	CP_MEASUREMENT_FLAG_EXTREME_FORCE_MAGNITUDES_PRESENT,
	CP_MEASUREMENT_FLAG_EXTREME_TORQUE_MAGNITUDES_PRESENT,
	CP_MEASUREMENT_FLAG_EXTREME_ANGLES_PRESENT,
	CP_MEASUREMENT_FLAG_TOP_DEAD_SPOT_ANGLE_PRESENT,
	CP_MEASUREMENT_FLAG_BOTTOM_DEAD_SPOT_ANGLE_PRESENT,
	CP_MEASUREMENT_FLAG_ACCUMULATED_ENERGY_PRESENT,
	CP_MEASUREMENT_FLAG_OFFSET_COMPENSATION_INDICATOR,
	CP_MEASUREMENT_FLAG_RESERVED
} cycling_pover_measurement_flag_t;

typedef enum {
	CP_SENSOR_LOCATION_OTHER,
	CP_SENSOR_LOCATION_TOP_OF_SHOE,
	CP_SENSOR_LOCATION_IN_SHOE,
	CP_SENSOR_LOCATION_HIP,
	CP_SENSOR_LOCATION_FRONT_WHEEL,
	CP_SENSOR_LOCATION_LEFT_CRANK,
	CP_SENSOR_LOCATION_RIGHT_CRANK,
	CP_SENSOR_LOCATION_LEFT_PEDAL,
	CP_SENSOR_LOCATION_RIGHT_PEDAL,
	CP_SENSOR_LOCATION_FRONT_HUB,
	CP_SENSOR_LOCATION_REAR_DROPOUT,
	CP_SENSOR_LOCATION_CHAINSTAY,
	CP_SENSOR_LOCATION_REAR_WHEEL,
	CP_SENSOR_LOCATION_REAR_HUB,
	CP_SENSOR_LOCATION_CHEST,
	CP_SENSOR_LOCATION_SPIDER,
	CP_SENSOR_LOCATION_CHAIN_RING,
	CP_SENSOR_LOCATION_RESERVED
} cycling_power_sensor_location_t;

typedef enum {
	CP_FEATURE_FLAG_PEDAL_POWER_BALANCE_SUPPORTED = 0,
	CP_FEATURE_FLAG_ACCUMULATED_TORQUE_SUPPORTED,
	CP_FEATURE_FLAG_WHEEL_REVOLUTION_DATA_SUPPORTED,
	CP_FEATURE_FLAG_CRANK_REVOLUTION_DATA_SUPPORTED,
	CP_FEATURE_FLAG_EXTREME_MAGNITUDES_SUPPORTED,
	CP_FEATURE_FLAG_EXTREME_ANGLES_SUPPORTED,
	CP_FEATURE_FLAG_TOP_AND_BOTTOM_DEAD_SPOT_ANGLE_SUPPORTED,
	CP_FEATURE_FLAG_ACCUMULATED_ENERGY_SUPPORTED,
	CP_FEATURE_FLAG_OFFSET_COMPENSATION_INDICATOR_SUPPORTED,
	CP_FEATURE_FLAG_OFFSET_COMPENSATION_SUPPORTED,
	CP_FEATURE_FLAG_CYCLING_POWER_MEASUREMENT_CHARACTERISTIC_CONTENT_MASKING_SUPPORTED,
	CP_FEATURE_FLAG_MULTIPLE_SENSOR_LOCATIONS_SUPPORTED,
	CP_FEATURE_FLAG_CRANK_LENGTH_ADJUSTMENT_SUPPORTED,
	CP_FEATURE_FLAG_CHAIN_LENGTH_ADJUSTMENT_SUPPORTED,
	CP_FEATURE_FLAG_CHAIN_WEIGHT_ADJUSTMENT_SUPPORTED,
	CP_FEATURE_FLAG_SPAN_LENGTH_ADJUSTMENT_SUPPORTED,
	CP_FEATURE_FLAG_SENSOR_MEASUREMENT_CONTEXT, // 0-force based, 1-torque based
	CP_FEATURE_FLAG_INSTANTANEOUS_MEASUREMENT_DIRECTION_SUPPORTED,
	CP_FEATURE_FLAG_FACTORY_CALIBRATION_DATE_SUPPORTED,
	CP_FEATURE_FLAG_ENHANCED_OFFSET_COMPENSATION_SUPPORTED,
	CP_FEATURE_FLAG_DISTRIBUTE_SYSTEM_SUPPORT,  // 0-unspecified, 1-not for use in distr. system, 2-used in distr. system, 3-reserved
	CP_FEATURE_FLAG_RESERVED
} cycling_power_feature_flag_t;

typedef enum {
	CP_VECTOR_FLAG_CRANK_REVOLUTION_DATA_PRESENT = 0,
	CP_VECTOR_FLAG_FIRST_CRANK_MEASUREMENT_ANGLE_PRESENT,
	CP_VECTOR_FLAG_INSTANTANEOUS_FORCE_MAGNITUDE_ARRAY_PRESENT,
	CP_VECTOR_FLAG_INSTANTANEOUS_TORQUE_MAGNITUDE_ARRAY_PRESENT,
	CP_VECTOR_FLAG_INSTANTANEOUS_MEASUREMENT_DIRECTION, // 0-Unknown, 1 - Tangential Component, 2 - Radial Component, 3 - Lateral Component
	CP_VECTOR_FLAG_RESERVED
} cycling_power_vector_flag_t;


/**
 * @brief Init Server with ATT DB
 */
void cycling_power_service_server_init(void);

/**
 * @brief Update heart rate (unit: beats per minute)
 * @note triggers notifications if subscribed
 */
void cycling_power_service_server_update_values(void);

/* API_END */

#if defined __cplusplus
}
#endif

#endif

